export interface Pin {
  id: string;
  title: string;
  description: string;
  author: string;
  seed: string; // Used for picsum
  heightRatio: number; // To simulate varying aspect ratios (e.g., 1.5 for portrait)
  color: string; // Dominant color placeholder
  tags: string[];
  isGenerated?: boolean;
  imageBase64?: string; // If generated by AI
}

export interface Comment {
  id: string;
  user: string;
  text: string;
  timestamp: string;
}

export interface User {
  id: string;
  name: string;
  handle: string;
  bio: string;
  avatar: string;
  isVerified: boolean; // For brands/companies
  isBusiness: boolean; // New: To distinguish business accounts
  followers: number;
  following: number;
}

export enum ViewState {
  FEED = 'FEED',
  DETAIL = 'DETAIL',
}